name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        uname -a
        grep -i authencesn /proc/crypto || true
        lsmod | grep alg || true
        modprobe algif_aead || true
        grep -i authencesn /proc/crypto || true
        lsmod | grep alg || true